//! End-to-end check against a real .pptx package.
//!
//! The fixture is generated by `fixtures/make_sample_pptx.py` so the repository
//! never has to carry a binary blob. If you do not have it locally, run:
//!
//! ```sh
//! python tests/fixtures/make_sample_pptx.py tests/fixtures/sample.pptx
//! ```

use std::path::{Path, PathBuf};

use deckr::ir::{BlockContent, Role};

fn fixture() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/sample.pptx")
}

fn load() -> Option<deckr::Deck> {
    let path = fixture();
    if !path.exists() {
        eprintln!(
            "skipping: {} is missing; generate it with tests/fixtures/make_sample_pptx.py",
            path.display()
        );
        return None;
    }
    Some(deckr::read_pptx(&path).expect("fixture parses"))
}

#[test]
fn slides_follow_presentation_order_not_filename_order() {
    let Some(deck) = load() else { return };
    // The fixture lists slide2.xml first in <p:sldIdLst>, so "deckr" must open
    // the deck even though slide1.xml sorts first on disk.
    assert_eq!(deck.len(), 2);
    assert_eq!(
        deck.slides[0].title().as_deref(),
        Some("deckr — a bidirectional deck engine")
    );
    assert_eq!(
        deck.slides[1].title().as_deref(),
        Some("Roadmap & Milestones")
    );
}

#[test]
fn bullets_keep_their_indent_levels() {
    let Some(deck) = load() else { return };
    let roadmap = &deck.slides[1];
    let body = roadmap
        .blocks
        .iter()
        .find(|b| b.role == Role::Body)
        .expect("a body placeholder");
    let text = body.as_text().expect("body holds text");
    let levels: Vec<u8> = text.paragraphs.iter().map(|p| p.level).collect();
    assert_eq!(levels, vec![0, 1, 2, 1]);
    assert_eq!(text.paragraphs[1].text, "OOXML & Deck IR");
}

#[test]
fn tables_charts_and_pictures_survive_the_package() {
    let Some(deck) = load() else { return };
    let roles: Vec<Role> = deck
        .slides
        .iter()
        .flat_map(|s| s.blocks.iter().map(|b| b.role))
        .collect();
    assert!(roles.contains(&Role::Table), "{roles:?}");
    assert!(roles.contains(&Role::Chart), "{roles:?}");
    assert!(roles.contains(&Role::Picture), "{roles:?}");
    assert!(roles.contains(&Role::Freeform), "{roles:?}");

    let table = deck
        .slides
        .iter()
        .flat_map(|s| s.blocks.iter())
        .find_map(|b| match &b.content {
            BlockContent::Table { rows } => Some(rows.clone()),
            _ => None,
        })
        .expect("a table");
    assert_eq!(table[0], vec!["Phase".to_string(), "Target".to_string()]);
    assert_eq!(
        table[1],
        vec!["0.1 read".to_string(), "2026 Q3".to_string()]
    );
}

#[test]
fn markdown_export_hides_chrome_and_empty_placeholders() {
    let Some(deck) = load() else { return };
    let md = deckr::markdown::to_markdown(&deck);

    assert!(
        md.contains("## Slide 1 — deckr — a bidirectional deck engine"),
        "{md}"
    );
    assert!(md.contains("- Ship the reader\n  - OOXML & Deck IR\n    - placeholders stay bound\n  - Write the builder\n"), "{md}");
    assert!(md.contains("| Phase | Target |"), "{md}");
    assert!(md.contains("`[chart]`"), "{md}");
    // The slide-number field must not leak, but genuinely free-floating text
    // on the canvas should still be exported.
    assert!(!md.contains("\n1\n"), "{md}");
    assert!(md.contains("internal only"), "{md}");
    assert!(!md.trim_end().ends_with("(no content)"), "{md}");
}

#[test]
fn json_round_trips() {
    let Some(deck) = load() else { return };
    let json = deckr::to_json(&deck).expect("serialises");
    let back = deckr::from_json(&json).expect("deserialises");
    assert_eq!(back.len(), deck.len());
    assert_eq!(back.outline(), deck.outline());
}
