//! End-to-end check of the `.potx` template-reuse feature (0.3).
//!
//! The template fixture (`tests/fixtures/template.potx`, generated by
//! `make_sample_pptx.py --template`) ships a deliberately *non-Office* theme:
//! its `accent1` is `C00000`, not the default `4472C4`. A build that genuinely
//! inherits the template must emit that theme, wire every chrome part into a
//! valid package, and still round-trip through deckr's own reader.

use std::collections::HashMap;
use std::io::{Cursor, Read};
use std::path::{Path, PathBuf};
use std::process::Command;

use deckr::Template;
use deckr::ir::{Block, BlockContent, Deck, Paragraph, Role, Slide, TextContent};

fn fixtures_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

fn template_path() -> PathBuf {
    fixtures_dir().join("template.potx")
}

/// Make sure the template fixture exists; generate it if we have Python.
fn ensure_template() -> Option<PathBuf> {
    let path = template_path();
    if path.exists() {
        return Some(path);
    }
    let py = fixtures_dir().join("make_sample_pptx.py");
    for exe in ["python3", "python"] {
        if Command::new(exe)
            .arg(&py)
            .arg("--template")
            .arg(&path)
            .status()
            .map(|s| s.success())
            .unwrap_or(false)
            && path.exists()
        {
            return Some(path);
        }
    }
    eprintln!(
        "skipping: {} is missing and Python was not available to generate it",
        path.display()
    );
    None
}

fn sample_deck() -> Deck {
    Deck {
        slides: vec![
            Slide {
                index: 0,
                blocks: vec![
                    Block {
                        role: Role::CenteredTitle,
                        content: BlockContent::Text(TextContent {
                            paragraphs: vec![Paragraph::new(0, "Quarterly Update")],
                        }),
                    },
                    Block {
                        role: Role::Subtitle,
                        content: BlockContent::Text(TextContent {
                            paragraphs: vec![Paragraph::new(0, "Q3 results")],
                        }),
                    },
                ],
            },
            Slide {
                index: 1,
                blocks: vec![
                    Block {
                        role: Role::Title,
                        content: BlockContent::Text(TextContent {
                            paragraphs: vec![Paragraph::new(0, "Roadmap")],
                        }),
                    },
                    Block {
                        role: Role::Body,
                        content: BlockContent::Text(TextContent {
                            paragraphs: vec![
                                Paragraph::new(0, "ship the reader"),
                                Paragraph::new(1, "keep it simple"),
                            ],
                        }),
                    },
                ],
            },
        ],
    }
}

fn build_with_template(deck: &Deck) -> (Vec<u8>, deckr::BuildReport) {
    let tpl = ensure_template().expect("template fixture");
    let tpl = Template::load(&tpl).expect("template loads");
    let mut buf: Vec<u8> = Vec::new();
    let report = deckr::write_pptx_template(deck, Cursor::new(&mut buf), &tpl).expect("writes");
    (buf, report)
}

/// Read every part of the package as text (the template test produces only
/// XML parts, so UTF-8 is safe) into a name -> contents map.
fn read_parts(buf: &[u8]) -> HashMap<String, String> {
    let mut pkg = zip::ZipArchive::new(Cursor::new(buf)).expect("a readable zip");
    let names: Vec<String> = pkg.file_names().map(|s| s.to_string()).collect();
    let mut out = HashMap::new();
    for name in names {
        let mut s = String::new();
        pkg.by_name(&name)
            .unwrap_or_else(|_| panic!("open {name}"))
            .read_to_string(&mut s)
            .unwrap_or_else(|_| panic!("utf8 {name}"));
        out.insert(name, s);
    }
    out
}

// ---------------------------------------------------------------------------
// OPC validity helpers
// ---------------------------------------------------------------------------

fn attr(seg: &str, name: &str) -> Option<String> {
    let pat = format!("{name}=\"");
    let s = seg.find(&pat)? + pat.len();
    let e = seg[s..].find('"')? + s;
    Some(seg[s..e].to_string())
}

/// Every `<Relationship>` in a `.rels` document: `(id, target, external)`.
fn rels_in(xml: &str) -> Vec<(String, String, bool)> {
    let mut out = Vec::new();
    for seg in xml.split("<Relationship") {
        let id = attr(seg, "Id");
        let target = attr(seg, "Target");
        let external = seg.contains("TargetMode=\"External\"");
        if let (Some(id), Some(target)) = (id, target) {
            out.push((id, target, external));
        }
    }
    out
}

/// The directory a `.rels` file resolves its targets against (the directory of
/// the part it describes, i.e. the parent of `_rels`).
fn rels_base(name: &str) -> String {
    // The package-root `.rels` has no parent directory to strip: its targets
    // resolve against `/`.
    if name.starts_with("_rels/") {
        return String::new();
    }
    let stripped = name.replacen("/_rels/", "/", 1);
    stripped
        .rsplit_once('/')
        .map(|(d, _)| d.to_string())
        .unwrap_or_default()
}

fn resolve(base: &str, target: &str) -> String {
    let mut parts: Vec<&str> = base.split('/').filter(|s| !s.is_empty()).collect();
    for seg in target.split('/') {
        match seg {
            "." | "" => {}
            ".." => {
                parts.pop();
            }
            s => parts.push(s),
        }
    }
    parts.join("/")
}

/// Whether `[Content_Types].xml` declares a content type for `name`.
fn declared(ct: &str, name: &str) -> bool {
    let part = format!("/{name}");
    for seg in ct.split("<Override") {
        if let Some(pn) = attr(seg, "PartName") {
            if pn == part {
                return true;
            }
        }
    }
    if let Some((_, ext)) = name.rsplit_once('.') {
        let ext = ext.to_lowercase();
        for seg in ct.split("<Default") {
            if let Some(e) = attr(seg, "Extension") {
                if e.to_lowercase() == ext {
                    return true;
                }
            }
        }
    }
    false
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[test]
fn template_build_inherits_the_templates_theme() {
    let (buf, _report) = build_with_template(&sample_deck());
    let parts = read_parts(&buf);

    let theme = &parts["ppt/theme/theme1.xml"];
    // The template's accent1 is C00000 — proof the theme was inherited.
    assert!(
        theme.contains("C00000"),
        "theme should inherit template accent1"
    );
    // The default Office accent1 must be gone: we did not write deckr's theme.
    assert!(
        !theme.contains("4472C4"),
        "theme must not be deckr's default Office accent1"
    );
}

#[test]
fn template_build_is_opc_valid() {
    let (buf, report) = build_with_template(&sample_deck());
    let parts = read_parts(&buf);

    assert_eq!(report.skipped_count(), 0, "{:?}", report.skipped);

    // Every part must have a declared content type.
    let ct = &parts["[Content_Types].xml"];
    for name in parts.keys() {
        assert!(
            declared(ct, name),
            "part {name} has no content-type declaration"
        );
    }

    // Every internal relationship must point at a part that exists.
    let names: std::collections::HashSet<String> = parts.keys().cloned().collect();
    for name in parts.keys() {
        if !name.ends_with(".rels") {
            continue;
        }
        let base = rels_base(name);
        for (_, target, external) in rels_in(&parts[name]) {
            if external {
                continue;
            }
            let resolved = resolve(&base, &target);
            assert!(
                names.contains(&resolved),
                "relationship in {name} -> {target} resolves to {resolved}, which is absent"
            );
        }
    }

    // presentation.xml.rels must reference the master, both slides, and the
    // three presentation-level chrome parts the template contributed.
    let pres_rels = &parts["ppt/_rels/presentation.xml.rels"];
    assert!(
        pres_rels.contains("relationships/slideMaster"),
        "presentation rels must reference the master"
    );
    assert_eq!(
        rels_in(pres_rels)
            .iter()
            .filter(|(_, t, _)| t.starts_with("slides/slide"))
            .count(),
        2,
        "presentation rels must reference both slides"
    );
    for want in ["presProps", "viewProps", "tableStyles"] {
        assert!(
            pres_rels.contains(&format!("relationships/{want}")),
            "presentation rels must reference {want}"
        );
    }

    // Each slide must bind to a template layout.
    for i in 1..=2 {
        let slide_rels = &parts[&format!("ppt/slides/_rels/slide{i}.xml.rels")];
        assert!(
            slide_rels.contains("relationships/slideLayout"),
            "slide{i} must reference a slide layout"
        );
    }
    // Slide 1 (title + body) should bind to the "Title and Content" layout.
    assert!(
        parts["ppt/slides/_rels/slide2.xml.rels"].contains("../slideLayouts/slideLayout2.xml"),
        "content slide must use the template's second layout"
    );
}

#[test]
fn template_build_binds_text_to_placeholders_and_round_trips() {
    let (buf, _report) = build_with_template(&sample_deck());
    let parts = read_parts(&buf);

    // The content slide carries a title and a body placeholder.
    let slide2 = &parts["ppt/slides/slide2.xml"];
    assert!(slide2.contains("<p:ph type=\"title\""), "{slide2}");
    assert!(slide2.contains("<p:ph type=\"body\""), "{slide2}");
    assert!(slide2.contains("ship the reader"), "{slide2}");

    // The generated package must re-open in deckr's own reader.
    let dir = std::env::temp_dir().join(format!("deckr-tpl-{}", std::process::id()));
    std::fs::create_dir_all(&dir).expect("tmpdir");
    let out = dir.join("from_template.pptx");
    std::fs::write(&out, &buf).expect("write");
    let back = deckr::read_pptx(&out).expect("the template-built package re-opens");
    assert_eq!(back.len(), 2);
    assert_eq!(back.slides[0].title().as_deref(), Some("Quarterly Update"));
    assert_eq!(back.slides[1].title().as_deref(), Some("Roadmap"));
    let _ = std::fs::remove_dir_all(&dir);
}

#[test]
fn template_build_is_deterministic() {
    let a = build_with_template(&sample_deck()).0;
    let b = build_with_template(&sample_deck()).0;
    assert_eq!(a, b, "template builds must be byte-identical");
}
