//! Deck IR -> Markdown.
//!
//! The export that makes a PPTX greppable, diffable and digestible by an LLM.
//! Every sentence here is also the reverse pipeline's input dialect: `deckr
//! build` reads this shape back and routes each block to the matching master
//! placeholder, which is why the Markdown round-trips rather than merely
//! documents.

use crate::ir::{Block, BlockContent, Deck, Paragraph, Role, Slide, TextContent};

/// Render a whole deck as Markdown. Slides are separated by `---`.
pub fn to_markdown(deck: &Deck) -> String {
    let mut out = String::new();
    for slide in &deck.slides {
        render_slide(&mut out, slide);
    }
    out
}

fn render_slide(out: &mut String, slide: &Slide) {
    let n = slide.index + 1;
    match slide.title() {
        Some(title) if !title.is_empty() => {
            out.push_str(&format!("\n---\n\n## Slide {n} — {title}\n\n"))
        }
        _ => out.push_str(&format!("\n---\n\n## Slide {n}\n\n")),
    }

    let mut rendered = 0;
    for block in &slide.blocks {
        // Title blocks already became the heading above; page furniture
        // (footer, date, slide number) is regenerated by the theme on rebuild,
        // so carrying it through would bake a duplicate into the Markdown.
        if block.role.is_chrome() || is_heading_role(block.role) || block.is_empty() {
            continue;
        }
        rendered += 1;
        match &block.content {
            BlockContent::Text(t) => render_text(out, block.role, t),
            BlockContent::Table { rows } => out.push_str(&render_table(rows)),
            BlockContent::Picture { alt } => {
                // TODO(0.4): resolve the real media filename from the slide's
                // relationship part instead of pointing at a placeholder.
                let alt = alt.clone().unwrap_or_else(|| "image".to_string());
                out.push_str(&format!("![{alt}](media://slide{n})\n\n"));
            }
            // Charts and diagrams cannot yet be re-authored from Markdown, so
            // they export as a marker that survives the round trip as itself.
            BlockContent::Chart { .. } => out.push_str("`[chart]`\n\n"),
            BlockContent::Diagram { .. } => out.push_str("`[diagram]`\n\n"),
            BlockContent::Empty => {}
        }
    }

    if rendered == 0 {
        out.push_str("_(no content)_\n\n");
    }
}

fn is_heading_role(role: Role) -> bool {
    matches!(role, Role::Title | Role::CenteredTitle)
}

fn render_text(out: &mut String, role: Role, text: &TextContent) {
    let paragraphs: Vec<&Paragraph> = text
        .paragraphs
        .iter()
        .filter(|p| !p.text.trim().is_empty())
        .collect();
    if paragraphs.is_empty() {
        return;
    }

    // A bullet list if the shape *is* a list placeholder, or if the author
    // indented anything. A lone title/thank-you caption stays a plain paragraph.
    let bulleted =
        matches!(role, Role::Body | Role::Object) || paragraphs.iter().any(|p| p.level > 0);

    for p in paragraphs {
        let body = if p.is_plain() {
            p.text.clone()
        } else {
            render_inline(p)
        };
        let indent = "  ".repeat(p.level as usize);
        for (i, line) in body.lines().enumerate() {
            let marker = if bulleted {
                // Continuation lines of a soft-broken bullet hang in.
                if i == 0 { "- " } else { "  " }
            } else {
                ""
            };
            let line = line.trim_end();
            if line.is_empty() {
                out.push('\n');
                continue;
            }
            out.push_str(&format!("{indent}{marker}{line}\n"));
        }
    }
    out.push('\n');
}

/// One paragraph's text with per-run Markdown emphasis applied.
///
/// The nesting order matters: a link sits innermost because Markdown treats it
/// as part of the visible text, and bold wraps everything so that
/// `**[label](url)**` renders as intended rather than as a literal.
fn render_inline(p: &Paragraph) -> String {
    p.display_runs()
        .iter()
        .map(|run| {
            let mut text = run.text.clone();
            if let Some(link) = &run.link {
                text = format!("[{text}]({link})");
            }
            if run.underline == Some(true) {
                text = format!("<u>{text}</u>");
            }
            if run.strike == Some(true) {
                text = format!("~~{text}~~");
            }
            if run.italic == Some(true) {
                text = format!("*{text}*");
            }
            if run.bold == Some(true) {
                text = format!("**{text}**");
            }
            text
        })
        .collect()
}

fn render_table(rows: &[Vec<String>]) -> String {
    let Some(width) = rows.iter().map(|r| r.len()).max().filter(|w| *w > 0) else {
        return String::new();
    };

    let mut out = String::new();
    let (header, body) = rows.split_first().unwrap();
    out.push('|');
    for c in 0..width {
        out.push_str(&format!(" {} |", cell(header, c)));
    }
    out.push('\n');
    out.push('|');
    for _ in 0..width {
        out.push_str(" --- |");
    }
    out.push('\n');
    for row in body {
        out.push('|');
        for c in 0..width {
            out.push_str(&format!(" {} |", cell(row, c)));
        }
        out.push('\n');
    }
    out.push('\n');
    out
}

fn cell(row: &[String], c: usize) -> String {
    row.get(c)
        .map(|s| s.trim())
        .unwrap_or_default()
        .replace('|', "\\|")
}

/// Render just the outline — one line per slide. Handy for `git diff`.
pub fn to_outline(deck: &Deck) -> String {
    let mut out = String::new();
    for (i, title) in deck.outline().iter().enumerate() {
        match title {
            Some(t) => out.push_str(&format!("{}. {t}\n", i + 1)),
            None => out.push_str(&format!("{}. (untitled)\n", i + 1)),
        }
    }
    out
}

/// Count blocks by role — the shape inventory of a deck.
pub fn role_histogram(deck: &Deck) -> Vec<(Role, usize)> {
    let mut counts: Vec<(Role, usize)> = Vec::new();
    for slide in &deck.slides {
        for Block { role, .. } in &slide.blocks {
            match counts.iter_mut().find(|(r, _)| r == role) {
                Some((_, n)) => *n += 1,
                None => counts.push((*role, 1)),
            }
        }
    }
    counts.sort_by_key(|(_, n)| std::cmp::Reverse(*n));
    counts
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::{Deck, Run, TextContent};

    fn text(slide: &Slide) -> Option<&TextContent> {
        slide.blocks.first().and_then(|b| b.as_text())
    }

    #[test]
    fn body_placeholders_render_as_a_bullet_list() {
        let deck = Deck {
            slides: vec![Slide {
                index: 0,
                blocks: vec![
                    Block {
                        role: Role::Title,
                        content: BlockContent::Text(TextContent {
                            paragraphs: vec![Paragraph::new(0, "Quarterly Review")],
                        }),
                    },
                    Block {
                        role: Role::Body,
                        content: BlockContent::Text(TextContent {
                            paragraphs: vec![
                                Paragraph::new(0, "revenue"),
                                Paragraph::new(1, "up 12%"),
                            ],
                        }),
                    },
                ],
            }],
        };

        let md = to_markdown(&deck);
        assert!(md.contains("## Slide 1 — Quarterly Review"), "{md}");
        assert!(md.contains("- revenue\n  - up 12%\n"), "{md}");
    }

    #[test]
    fn empty_placeholders_and_chrome_are_not_exported() {
        let deck = Deck {
            slides: vec![Slide {
                index: 0,
                blocks: vec![
                    Block {
                        role: Role::Body,
                        content: BlockContent::Text(TextContent { paragraphs: vec![] }),
                    },
                    Block {
                        role: Role::SlideNumber,
                        content: BlockContent::Text(TextContent {
                            paragraphs: vec![Paragraph::new(0, "7")],
                        }),
                    },
                ],
            }],
        };
        let md = to_markdown(&deck);
        assert!(md.contains("_(no content)_"), "{md}");
        assert!(!md.contains('7'), "{md}");
    }

    #[test]
    fn tables_become_github_flavoured_markdown() {
        let rows = vec![
            vec!["Region".into(), "Q3".into()],
            vec!["APAC".into(), "1.2".into()],
        ];
        let md = render_table(&rows);
        assert_eq!(md, "| Region | Q3 |\n| --- | --- |\n| APAC | 1.2 |\n\n");
    }

    #[test]
    fn pipes_inside_cells_are_escaped() {
        let rows = vec![vec!["a|b".into()]];
        assert!(render_table(&rows).contains("a\\|b"));
    }

    #[test]
    fn runs_export_as_markdown_emphasis() {
        let deck = Deck {
            slides: vec![Slide {
                index: 0,
                blocks: vec![Block {
                    role: Role::Body,
                    content: BlockContent::Text(TextContent {
                        paragraphs: vec![Paragraph::from_runs(
                            0,
                            vec![
                                Run {
                                    text: "urgent".into(),
                                    bold: Some(true),
                                    ..Default::default()
                                },
                                Run::new(" and "),
                                Run {
                                    text: "noted".into(),
                                    italic: Some(true),
                                    ..Default::default()
                                },
                            ],
                        )],
                    }),
                }],
            }],
        };
        let md = to_markdown(&deck);
        assert!(md.contains("- **urgent** and *noted*"), "{md}");
    }

    #[test]
    fn links_wrap_the_innermost_text() {
        let run = Run {
            text: "report".into(),
            bold: Some(true),
            link: Some("https://example.com/r".into()),
            ..Default::default()
        };
        let md = render_inline(&Paragraph::from_runs(0, vec![run]));
        assert_eq!(md, "**[report](https://example.com/r)**");
    }

    #[test]
    fn a_soft_break_inside_a_styled_paragraph_keeps_hanging_indent() {
        let p = Paragraph::from_runs(
            0,
            vec![
                Run {
                    text: "head".into(),
                    bold: Some(true),
                    ..Default::default()
                },
                Run::new("tail\nsecond line"),
            ],
        );
        let md = render_inline(&p);
        assert_eq!(md, "**head**tail\nsecond line");
    }

    #[test]
    fn outline_lists_every_slide() {
        let deck = Deck {
            slides: vec![
                Slide {
                    index: 0,
                    blocks: vec![Block {
                        role: Role::Title,
                        content: BlockContent::Text(TextContent {
                            paragraphs: vec![Paragraph::new(0, "Intro")],
                        }),
                    }],
                },
                Slide {
                    index: 1,
                    blocks: vec![],
                },
            ],
        };
        assert_eq!(to_outline(&deck), "1. Intro\n2. (untitled)\n");
        assert!(text(&deck.slides[0]).is_some());
    }
}
