//! Deck IR -> Markdown.
//!
//! The export that makes a PPTX greppable, diffable and digestible by an LLM.
//! Every sentence here is also the reverse pipeline's input dialect: `deckr
//! build` will read this shape back and route each block to the matching master
//! placeholder.

use crate::ir::{Block, BlockContent, Deck, Paragraph, Role, Slide, TextContent};

/// Render a whole deck as Markdown. Slides are separated by `---`.
pub fn to_markdown(deck: &Deck) -> String {
    let mut out = String::new();
    for slide in &deck.slides {
        render_slide(&mut out, slide);
    }
    out
}

fn render_slide(out: &mut String, slide: &Slide) {
    let n = slide.index + 1;
    match slide.title() {
        Some(title) if !title.is_empty() => {
            out.push_str(&format!("\n---\n\n## Slide {n} — {title}\n\n"))
        }
        _ => out.push_str(&format!("\n---\n\n## Slide {n}\n\n")),
    }

    let mut rendered = 0;
    for block in &slide.blocks {
        // Title blocks already became the heading above; page furniture
        // (footer, date, slide number) is regenerated by the theme on rebuild,
        // so carrying it through would bake a duplicate into the Markdown.
        if block.role.is_chrome() || is_heading_role(block.role) || block.is_empty() {
            continue;
        }
        rendered += 1;
        match &block.content {
            BlockContent::Text(t) => render_text(out, block.role, t),
            BlockContent::Table { rows } => out.push_str(&render_table(rows)),
            BlockContent::Picture { alt } => {
                // TODO(0.4): resolve the real media filename from the slide's
                // relationship part instead of pointing at a placeholder.
                let alt = alt.clone().unwrap_or_else(|| "image".to_string());
                out.push_str(&format!("![{alt}](media://slide{n})\n\n"));
            }
            // Phase 0 records that the object is there. Restoring the numbers
            // behind it lands in 0.4 (`ChartData`).
            BlockContent::Chart { .. } => out.push_str("`[chart]`\n\n"),
            BlockContent::Diagram { .. } => out.push_str("`[diagram]`\n\n"),
            BlockContent::Empty => {}
        }
    }

    if rendered == 0 {
        out.push_str("_(no content)_\n\n");
    }
}

fn is_heading_role(role: Role) -> bool {
    matches!(role, Role::Title | Role::CenteredTitle)
}

fn render_text(out: &mut String, role: Role, text: &TextContent) {
    let paragraphs: Vec<&Paragraph> = text
        .paragraphs
        .iter()
        .filter(|p| !p.text.trim().is_empty())
        .collect();
    if paragraphs.is_empty() {
        return;
    }

    // A bullet list if the shape *is* a list placeholder, or if the author
    // indented anything. A lone title/thank-you caption stays a plain paragraph.
    let bulleted =
        matches!(role, Role::Body | Role::Object) || paragraphs.iter().any(|p| p.level > 0);

    for p in paragraphs {
        let indent = "  ".repeat(p.level as usize);
        for (i, line) in p.text.lines().enumerate() {
            let line = line.trim();
            if bulleted {
                // Continuation lines of a soft-broken bullet hang in.
                let marker = if i == 0 { "- " } else { "  " };
                out.push_str(&format!("{indent}{marker}{line}\n"));
            } else {
                out.push_str(&format!("{line}\n"));
            }
        }
    }
    out.push('\n');
}

fn render_table(rows: &[Vec<String>]) -> String {
    let Some(width) = rows.iter().map(|r| r.len()).max().filter(|w| *w > 0) else {
        return String::new();
    };

    let mut out = String::new();
    let (header, body) = rows.split_first().unwrap();
    out.push('|');
    for c in 0..width {
        out.push_str(&format!(" {} |", cell(header, c)));
    }
    out.push('\n');
    out.push('|');
    for _ in 0..width {
        out.push_str(" --- |");
    }
    out.push('\n');
    for row in body {
        out.push('|');
        for c in 0..width {
            out.push_str(&format!(" {} |", cell(row, c)));
        }
        out.push('\n');
    }
    out.push('\n');
    out
}

fn cell(row: &[String], c: usize) -> String {
    row.get(c)
        .map(|s| s.trim())
        .unwrap_or_default()
        .replace('|', "\\|")
}

/// Render just the outline — one line per slide. Handy for `git diff`.
pub fn to_outline(deck: &Deck) -> String {
    let mut out = String::new();
    for (i, title) in deck.outline().iter().enumerate() {
        match title {
            Some(t) => out.push_str(&format!("{}. {t}\n", i + 1)),
            None => out.push_str(&format!("{}. (untitled)\n", i + 1)),
        }
    }
    out
}

/// Count blocks by role — the shape inventory of a deck.
pub fn role_histogram(deck: &Deck) -> Vec<(Role, usize)> {
    let mut counts: Vec<(Role, usize)> = Vec::new();
    for slide in &deck.slides {
        for Block { role, .. } in &slide.blocks {
            match counts.iter_mut().find(|(r, _)| r == role) {
                Some((_, n)) => *n += 1,
                None => counts.push((*role, 1)),
            }
        }
    }
    counts.sort_by_key(|(_, n)| std::cmp::Reverse(*n));
    counts
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::{Deck, TextContent};

    fn text(slide: &Slide) -> Option<&TextContent> {
        slide.blocks.first().and_then(|b| b.as_text())
    }

    #[test]
    fn body_placeholders_render_as_a_bullet_list() {
        let deck = Deck {
            slides: vec![Slide {
                index: 0,
                blocks: vec![
                    Block {
                        role: Role::Title,
                        content: BlockContent::Text(TextContent {
                            paragraphs: vec![Paragraph {
                                level: 0,
                                text: "Quarterly Review".into(),
                            }],
                        }),
                    },
                    Block {
                        role: Role::Body,
                        content: BlockContent::Text(TextContent {
                            paragraphs: vec![
                                Paragraph {
                                    level: 0,
                                    text: "revenue".into(),
                                },
                                Paragraph {
                                    level: 1,
                                    text: "up 12%".into(),
                                },
                            ],
                        }),
                    },
                ],
            }],
        };

        let md = to_markdown(&deck);
        assert!(md.contains("## Slide 1 — Quarterly Review"), "{md}");
        assert!(md.contains("- revenue\n  - up 12%\n"), "{md}");
    }

    #[test]
    fn empty_placeholders_and_chrome_are_not_exported() {
        let deck = Deck {
            slides: vec![Slide {
                index: 0,
                blocks: vec![
                    Block {
                        role: Role::Body,
                        content: BlockContent::Text(TextContent { paragraphs: vec![] }),
                    },
                    Block {
                        role: Role::SlideNumber,
                        content: BlockContent::Text(TextContent {
                            paragraphs: vec![Paragraph {
                                level: 0,
                                text: "7".into(),
                            }],
                        }),
                    },
                ],
            }],
        };
        let md = to_markdown(&deck);
        assert!(md.contains("_(no content)_"), "{md}");
        assert!(!md.contains('7'), "{md}");
    }

    #[test]
    fn tables_become_github_flavoured_markdown() {
        let rows = vec![
            vec!["Region".into(), "Q3".into()],
            vec!["APAC".into(), "1.2".into()],
        ];
        let md = render_table(&rows);
        assert_eq!(md, "| Region | Q3 |\n| --- | --- |\n| APAC | 1.2 |\n\n");
    }

    #[test]
    fn pipes_inside_cells_are_escaped() {
        let rows = vec![vec!["a|b".into()]];
        assert!(render_table(&rows).contains("a\\|b"));
    }

    #[test]
    fn outline_lists_every_slide() {
        let deck = Deck {
            slides: vec![
                Slide {
                    index: 0,
                    blocks: vec![Block {
                        role: Role::Title,
                        content: BlockContent::Text(TextContent {
                            paragraphs: vec![Paragraph {
                                level: 0,
                                text: "Intro".into(),
                            }],
                        }),
                    }],
                },
                Slide {
                    index: 1,
                    blocks: vec![],
                },
            ],
        };
        assert_eq!(to_outline(&deck), "1. Intro\n2. (untitled)\n");
        assert!(text(&deck.slides[0]).is_some());
    }
}
